# Generated by Django 5.2.5 on 2026-07-14 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], default='processing', max_length=12)),
                ('rendered_message', models.TextField(blank=True)),
                ('weather_snapshot', models.JSONField(blank=True, default=dict)),
                ('provider_sid', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='scheduling.scheduledevent')),
            ],
            options={
                'ordering': ['event', 'attempt_number'],
                'constraints': [models.UniqueConstraint(fields=('event', 'attempt_number'), name='unique_delivery_attempt_number')],
            },
        ),
    ]
