# Generated by Django 5.2.5 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryattempt",
            name="provider_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("queued", "Queued"),
                    ("initiated", "Initiated"),
                    ("ringing", "Ringing"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("busy", "Busy"),
                    ("no_answer", "No answer"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="provider_status_sequence",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deliveryattempt",
            name="provider_status_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
