# Generated by Django 5.2.5 on 2026-07-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_deliveryattempt_provider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattempt',
            name='voice_action_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='voice_action_digit',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='voice_action_result',
            field=models.CharField(blank=True, choices=[('cancelled', 'Cancelled next event'), ('switched_to_sms', 'Switched next event to SMS'), ('no_pending_event', 'No pending event')], max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='voice_action_target_event_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
