# Generated by Django 5.2.5 on 2026-07-15 23:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryattempt_voice_action_completed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundSmsCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_sid', models.CharField(max_length=64, unique=True)),
                ('command', models.CharField(choices=[('stop', 'Stop next event'), ('sms', 'Switch next event to SMS'), ('time', 'Change next event time'), ('invalid', 'Invalid command')], max_length=12)),
                ('result', models.CharField(choices=[('cancelled', 'Cancelled next event'), ('switched_to_sms', 'Switched next event to SMS'), ('rescheduled', 'Rescheduled next event'), ('no_pending_event', 'No pending event'), ('unknown_sender', 'Unknown or unverified sender'), ('invalid_command', 'Invalid command'), ('invalid_time', 'Invalid time'), ('lifecycle_conflict', 'Lifecycle conflict')], max_length=24)),
                ('target_event_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-completed_at', '-id'],
            },
        ),
    ]
