# Generated by Django 5.2.5 on 2026-07-14 23:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_phonenumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Enter a five-digit US ZIP code.', regex='^\\d{5}$')])),
                ('scheduled_for', models.DateTimeField()),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('voice', 'Voice')], max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('is_demo', models.BooleanField(default=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_events', to='accounts.phonenumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_for'],
                'indexes': [models.Index(fields=['status', 'scheduled_for'], name='scheduling__status_58e9db_idx'), models.Index(fields=['user', 'scheduled_for'], name='scheduling__user_id_e516e1_idx')],
            },
        ),
    ]
